### ISSUE TITLE
Issues on npm install

### ISSUE THREAD

**Issue by gc-o** [chung-leong/relaks-wordpress-example#4]
Running NPM install we get the following log:

> added 904 packages from 544 contributors and audited 7999 packages in 132.216s
found 2 vulnerabilities (1 low, 1 high)

on `npm audit`

> Low             Regular Expression Denial of Service                                                                                                        
> Package         braces                                                        
> Dependency of   webpack-dev-server [dev]                                      
> Path            webpack-dev-server > http-proxy-middleware > micromatch > braces                                                        
> More info       https://nodesecurity.io/advisories/786                        
                                                                                
>  High            Missing Origin Validation                                     
>Package         webpack-dev-server          
>Dependency of   webpack-dev-server [dev]       
>Path            webpack-dev-server  
>More info       https://nodesecurity.io/advisories/725

I went through the rabbit hole and it seems that updating to the latest version of webpack-dev-server works OK on start-server but breaks the build and start at least on my computer (Windows 10). 

Is this a problem? What are the other ways to go?

**Comment by chung-leong** [comment]
Yeah, I ran into build problem with the latest version of WebPack Dev Server. Since it isn't part of the production system, I figured I would wait for it to resolve itself eventually.

**Comment by chung-leong** [comment]
This is fixed.

```
                       === npm audit security report ===                        
                                                                                
found 0 vulnerabilities
 in 10182 scanned packages
```
